/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.biovotion;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Heart rate calculated by biovotion device. */
@org.apache.avro.specific.AvroGenerated
public class BiovotionVSMHeartRate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6101405888794043353L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BiovotionVSMHeartRate\",\"namespace\":\"org.radarcns.biovotion\",\"doc\":\"Heart rate calculated by biovotion device.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"HeartRateValue\",\"type\":\"float\",\"doc\":\"Heart rate value (bpm)\"},{\"name\":\"HeartRateQuality\",\"type\":\"int\",\"doc\":\"Heart rate quality (%)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** Heart rate value (bpm) */
  @Deprecated public float HeartRateValue;
  /** Heart rate quality (%) */
  @Deprecated public int HeartRateQuality;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BiovotionVSMHeartRate() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param HeartRateValue Heart rate value (bpm)
   * @param HeartRateQuality Heart rate quality (%)
   */
  public BiovotionVSMHeartRate(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float HeartRateValue, java.lang.Integer HeartRateQuality) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.HeartRateValue = HeartRateValue;
    this.HeartRateQuality = HeartRateQuality;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return HeartRateValue;
    case 3: return HeartRateQuality;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: HeartRateValue = (java.lang.Float)value$; break;
    case 3: HeartRateQuality = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'HeartRateValue' field.
   * @return Heart rate value (bpm)
   */
  public java.lang.Float getHeartRateValue() {
    return HeartRateValue;
  }

  /**
   * Sets the value of the 'HeartRateValue' field.
   * Heart rate value (bpm)
   * @param value the value to set.
   */
  public void setHeartRateValue(java.lang.Float value) {
    this.HeartRateValue = value;
  }

  /**
   * Gets the value of the 'HeartRateQuality' field.
   * @return Heart rate quality (%)
   */
  public java.lang.Integer getHeartRateQuality() {
    return HeartRateQuality;
  }

  /**
   * Sets the value of the 'HeartRateQuality' field.
   * Heart rate quality (%)
   * @param value the value to set.
   */
  public void setHeartRateQuality(java.lang.Integer value) {
    this.HeartRateQuality = value;
  }

  /**
   * Creates a new BiovotionVSMHeartRate RecordBuilder.
   * @return A new BiovotionVSMHeartRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMHeartRate.Builder newBuilder() {
    return new org.radarcns.biovotion.BiovotionVSMHeartRate.Builder();
  }

  /**
   * Creates a new BiovotionVSMHeartRate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BiovotionVSMHeartRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMHeartRate.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMHeartRate.Builder other) {
    return new org.radarcns.biovotion.BiovotionVSMHeartRate.Builder(other);
  }

  /**
   * Creates a new BiovotionVSMHeartRate RecordBuilder by copying an existing BiovotionVSMHeartRate instance.
   * @param other The existing instance to copy.
   * @return A new BiovotionVSMHeartRate RecordBuilder
   */
  public static org.radarcns.biovotion.BiovotionVSMHeartRate.Builder newBuilder(org.radarcns.biovotion.BiovotionVSMHeartRate other) {
    return new org.radarcns.biovotion.BiovotionVSMHeartRate.Builder(other);
  }

  /**
   * RecordBuilder for BiovotionVSMHeartRate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BiovotionVSMHeartRate>
    implements org.apache.avro.data.RecordBuilder<BiovotionVSMHeartRate> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** Heart rate value (bpm) */
    private float HeartRateValue;
    /** Heart rate quality (%) */
    private int HeartRateQuality;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMHeartRate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.HeartRateValue)) {
        this.HeartRateValue = data().deepCopy(fields()[2].schema(), other.HeartRateValue);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.HeartRateQuality)) {
        this.HeartRateQuality = data().deepCopy(fields()[3].schema(), other.HeartRateQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BiovotionVSMHeartRate instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.biovotion.BiovotionVSMHeartRate other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.HeartRateValue)) {
        this.HeartRateValue = data().deepCopy(fields()[2].schema(), other.HeartRateValue);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.HeartRateQuality)) {
        this.HeartRateQuality = data().deepCopy(fields()[3].schema(), other.HeartRateQuality);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'HeartRateValue' field.
      * Heart rate value (bpm)
      * @return The value.
      */
    public java.lang.Float getHeartRateValue() {
      return HeartRateValue;
    }

    /**
      * Sets the value of the 'HeartRateValue' field.
      * Heart rate value (bpm)
      * @param value The value of 'HeartRateValue'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder setHeartRateValue(float value) {
      validate(fields()[2], value);
      this.HeartRateValue = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'HeartRateValue' field has been set.
      * Heart rate value (bpm)
      * @return True if the 'HeartRateValue' field has been set, false otherwise.
      */
    public boolean hasHeartRateValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'HeartRateValue' field.
      * Heart rate value (bpm)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder clearHeartRateValue() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'HeartRateQuality' field.
      * Heart rate quality (%)
      * @return The value.
      */
    public java.lang.Integer getHeartRateQuality() {
      return HeartRateQuality;
    }

    /**
      * Sets the value of the 'HeartRateQuality' field.
      * Heart rate quality (%)
      * @param value The value of 'HeartRateQuality'.
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder setHeartRateQuality(int value) {
      validate(fields()[3], value);
      this.HeartRateQuality = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'HeartRateQuality' field has been set.
      * Heart rate quality (%)
      * @return True if the 'HeartRateQuality' field has been set, false otherwise.
      */
    public boolean hasHeartRateQuality() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'HeartRateQuality' field.
      * Heart rate quality (%)
      * @return This builder.
      */
    public org.radarcns.biovotion.BiovotionVSMHeartRate.Builder clearHeartRateQuality() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public BiovotionVSMHeartRate build() {
      try {
        BiovotionVSMHeartRate record = new BiovotionVSMHeartRate();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.HeartRateValue = fieldSetFlags()[2] ? this.HeartRateValue : (java.lang.Float) defaultValue(fields()[2]);
        record.HeartRateQuality = fieldSetFlags()[3] ? this.HeartRateQuality : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
