/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phoneSensors;  
@SuppressWarnings("all")
/**  */
@org.apache.avro.specific.AvroGenerated
public class AndroidStatusServer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AndroidStatusServer\",\"namespace\":\"org.radarcns.phoneSensors\",\"doc\":\"\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"serverStatus\",\"type\":\"int\",\"doc\":\"0-disconnected,1-connected,2-failed uploading,3-other\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** 0-disconnected,1-connected,2-failed uploading,3-other */
  @Deprecated public int serverStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AndroidStatusServer() {}

  /**
   * All-args constructor.
   */
  public AndroidStatusServer(java.lang.Double time, java.lang.Double timeReceived, java.lang.Integer serverStatus) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.serverStatus = serverStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return serverStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: serverStatus = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'serverStatus' field.
   * 0-disconnected,1-connected,2-failed uploading,3-other   */
  public java.lang.Integer getServerStatus() {
    return serverStatus;
  }

  /**
   * Sets the value of the 'serverStatus' field.
   * 0-disconnected,1-connected,2-failed uploading,3-other   * @param value the value to set.
   */
  public void setServerStatus(java.lang.Integer value) {
    this.serverStatus = value;
  }

  /** Creates a new AndroidStatusServer RecordBuilder */
  public static org.radarcns.phoneSensors.AndroidStatusServer.Builder newBuilder() {
    return new org.radarcns.phoneSensors.AndroidStatusServer.Builder();
  }
  
  /** Creates a new AndroidStatusServer RecordBuilder by copying an existing Builder */
  public static org.radarcns.phoneSensors.AndroidStatusServer.Builder newBuilder(org.radarcns.phoneSensors.AndroidStatusServer.Builder other) {
    return new org.radarcns.phoneSensors.AndroidStatusServer.Builder(other);
  }
  
  /** Creates a new AndroidStatusServer RecordBuilder by copying an existing AndroidStatusServer instance */
  public static org.radarcns.phoneSensors.AndroidStatusServer.Builder newBuilder(org.radarcns.phoneSensors.AndroidStatusServer other) {
    return new org.radarcns.phoneSensors.AndroidStatusServer.Builder(other);
  }
  
  /**
   * RecordBuilder for AndroidStatusServer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AndroidStatusServer>
    implements org.apache.avro.data.RecordBuilder<AndroidStatusServer> {

    private double time;
    private double timeReceived;
    private int serverStatus;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.phoneSensors.AndroidStatusServer.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.phoneSensors.AndroidStatusServer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serverStatus)) {
        this.serverStatus = data().deepCopy(fields()[2].schema(), other.serverStatus);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AndroidStatusServer instance */
    private Builder(org.radarcns.phoneSensors.AndroidStatusServer other) {
            super(org.radarcns.phoneSensors.AndroidStatusServer.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serverStatus)) {
        this.serverStatus = data().deepCopy(fields()[2].schema(), other.serverStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'serverStatus' field */
    public java.lang.Integer getServerStatus() {
      return serverStatus;
    }
    
    /** Sets the value of the 'serverStatus' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder setServerStatus(int value) {
      validate(fields()[2], value);
      this.serverStatus = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'serverStatus' field has been set */
    public boolean hasServerStatus() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'serverStatus' field */
    public org.radarcns.phoneSensors.AndroidStatusServer.Builder clearServerStatus() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public AndroidStatusServer build() {
      try {
        AndroidStatusServer record = new AndroidStatusServer();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.serverStatus = fieldSetFlags()[2] ? this.serverStatus : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
