/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.phoneSensors;  
@SuppressWarnings("all")
/** Logs change of user interaction state: when the phone is unlocked or set to standby. */
@org.apache.avro.specific.AvroGenerated
public class PhoneSensorUserInteraction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneSensorUserInteraction\",\"namespace\":\"org.radarcns.phoneSensors\",\"doc\":\"Logs change of user interaction state: when the phone is unlocked or set to standby.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"interactionState\",\"type\":\"int\",\"doc\":\"0-standby, 1-unlocked\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** 0-standby, 1-unlocked */
  @Deprecated public int interactionState;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PhoneSensorUserInteraction() {}

  /**
   * All-args constructor.
   */
  public PhoneSensorUserInteraction(java.lang.Double time, java.lang.Double timeReceived, java.lang.Integer interactionState) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.interactionState = interactionState;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return interactionState;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: interactionState = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'interactionState' field.
   * 0-standby, 1-unlocked   */
  public java.lang.Integer getInteractionState() {
    return interactionState;
  }

  /**
   * Sets the value of the 'interactionState' field.
   * 0-standby, 1-unlocked   * @param value the value to set.
   */
  public void setInteractionState(java.lang.Integer value) {
    this.interactionState = value;
  }

  /** Creates a new PhoneSensorUserInteraction RecordBuilder */
  public static org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder newBuilder() {
    return new org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder();
  }
  
  /** Creates a new PhoneSensorUserInteraction RecordBuilder by copying an existing Builder */
  public static org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder newBuilder(org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder other) {
    return new org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder(other);
  }
  
  /** Creates a new PhoneSensorUserInteraction RecordBuilder by copying an existing PhoneSensorUserInteraction instance */
  public static org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder newBuilder(org.radarcns.phoneSensors.PhoneSensorUserInteraction other) {
    return new org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder(other);
  }
  
  /**
   * RecordBuilder for PhoneSensorUserInteraction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneSensorUserInteraction>
    implements org.apache.avro.data.RecordBuilder<PhoneSensorUserInteraction> {

    private double time;
    private double timeReceived;
    private int interactionState;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.phoneSensors.PhoneSensorUserInteraction.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.interactionState)) {
        this.interactionState = data().deepCopy(fields()[2].schema(), other.interactionState);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PhoneSensorUserInteraction instance */
    private Builder(org.radarcns.phoneSensors.PhoneSensorUserInteraction other) {
            super(org.radarcns.phoneSensors.PhoneSensorUserInteraction.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.interactionState)) {
        this.interactionState = data().deepCopy(fields()[2].schema(), other.interactionState);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'interactionState' field */
    public java.lang.Integer getInteractionState() {
      return interactionState;
    }
    
    /** Sets the value of the 'interactionState' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder setInteractionState(int value) {
      validate(fields()[2], value);
      this.interactionState = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'interactionState' field has been set */
    public boolean hasInteractionState() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'interactionState' field */
    public org.radarcns.phoneSensors.PhoneSensorUserInteraction.Builder clearInteractionState() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PhoneSensorUserInteraction build() {
      try {
        PhoneSensorUserInteraction record = new PhoneSensorUserInteraction();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.interactionState = fieldSetFlags()[2] ? this.interactionState : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
