/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.application;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Number of records cached or created. */
@org.apache.avro.specific.AvroGenerated
public class ApplicationRecordCounts extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6995182605271622097L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationRecordCounts\",\"namespace\":\"org.radarcns.application\",\"doc\":\"Number of records cached or created.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"recordsCached\",\"type\":\"int\",\"doc\":\"number of records currently being cached\",\"default\":-1},{\"name\":\"recordsSent\",\"type\":\"int\",\"doc\":\"number of records sent since application start\"},{\"name\":\"recordsUnsent\",\"type\":\"int\",\"doc\":\"number of unsent records\",\"default\":-1}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** number of records currently being cached */
  @Deprecated public int recordsCached;
  /** number of records sent since application start */
  @Deprecated public int recordsSent;
  /** number of unsent records */
  @Deprecated public int recordsUnsent;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationRecordCounts() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param recordsCached number of records currently being cached
   * @param recordsSent number of records sent since application start
   * @param recordsUnsent number of unsent records
   */
  public ApplicationRecordCounts(java.lang.Double time, java.lang.Double timeReceived, java.lang.Integer recordsCached, java.lang.Integer recordsSent, java.lang.Integer recordsUnsent) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.recordsCached = recordsCached;
    this.recordsSent = recordsSent;
    this.recordsUnsent = recordsUnsent;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return recordsCached;
    case 3: return recordsSent;
    case 4: return recordsUnsent;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: recordsCached = (java.lang.Integer)value$; break;
    case 3: recordsSent = (java.lang.Integer)value$; break;
    case 4: recordsUnsent = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'recordsCached' field.
   * @return number of records currently being cached
   */
  public java.lang.Integer getRecordsCached() {
    return recordsCached;
  }

  /**
   * Sets the value of the 'recordsCached' field.
   * number of records currently being cached
   * @param value the value to set.
   */
  public void setRecordsCached(java.lang.Integer value) {
    this.recordsCached = value;
  }

  /**
   * Gets the value of the 'recordsSent' field.
   * @return number of records sent since application start
   */
  public java.lang.Integer getRecordsSent() {
    return recordsSent;
  }

  /**
   * Sets the value of the 'recordsSent' field.
   * number of records sent since application start
   * @param value the value to set.
   */
  public void setRecordsSent(java.lang.Integer value) {
    this.recordsSent = value;
  }

  /**
   * Gets the value of the 'recordsUnsent' field.
   * @return number of unsent records
   */
  public java.lang.Integer getRecordsUnsent() {
    return recordsUnsent;
  }

  /**
   * Sets the value of the 'recordsUnsent' field.
   * number of unsent records
   * @param value the value to set.
   */
  public void setRecordsUnsent(java.lang.Integer value) {
    this.recordsUnsent = value;
  }

  /**
   * Creates a new ApplicationRecordCounts RecordBuilder.
   * @return A new ApplicationRecordCounts RecordBuilder
   */
  public static org.radarcns.application.ApplicationRecordCounts.Builder newBuilder() {
    return new org.radarcns.application.ApplicationRecordCounts.Builder();
  }

  /**
   * Creates a new ApplicationRecordCounts RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationRecordCounts RecordBuilder
   */
  public static org.radarcns.application.ApplicationRecordCounts.Builder newBuilder(org.radarcns.application.ApplicationRecordCounts.Builder other) {
    return new org.radarcns.application.ApplicationRecordCounts.Builder(other);
  }

  /**
   * Creates a new ApplicationRecordCounts RecordBuilder by copying an existing ApplicationRecordCounts instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationRecordCounts RecordBuilder
   */
  public static org.radarcns.application.ApplicationRecordCounts.Builder newBuilder(org.radarcns.application.ApplicationRecordCounts other) {
    return new org.radarcns.application.ApplicationRecordCounts.Builder(other);
  }

  /**
   * RecordBuilder for ApplicationRecordCounts instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationRecordCounts>
    implements org.apache.avro.data.RecordBuilder<ApplicationRecordCounts> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** number of records currently being cached */
    private int recordsCached;
    /** number of records sent since application start */
    private int recordsSent;
    /** number of unsent records */
    private int recordsUnsent;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.application.ApplicationRecordCounts.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.recordsCached)) {
        this.recordsCached = data().deepCopy(fields()[2].schema(), other.recordsCached);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.recordsSent)) {
        this.recordsSent = data().deepCopy(fields()[3].schema(), other.recordsSent);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.recordsUnsent)) {
        this.recordsUnsent = data().deepCopy(fields()[4].schema(), other.recordsUnsent);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationRecordCounts instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.application.ApplicationRecordCounts other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.recordsCached)) {
        this.recordsCached = data().deepCopy(fields()[2].schema(), other.recordsCached);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.recordsSent)) {
        this.recordsSent = data().deepCopy(fields()[3].schema(), other.recordsSent);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.recordsUnsent)) {
        this.recordsUnsent = data().deepCopy(fields()[4].schema(), other.recordsUnsent);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordsCached' field.
      * number of records currently being cached
      * @return The value.
      */
    public java.lang.Integer getRecordsCached() {
      return recordsCached;
    }

    /**
      * Sets the value of the 'recordsCached' field.
      * number of records currently being cached
      * @param value The value of 'recordsCached'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder setRecordsCached(int value) {
      validate(fields()[2], value);
      this.recordsCached = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'recordsCached' field has been set.
      * number of records currently being cached
      * @return True if the 'recordsCached' field has been set, false otherwise.
      */
    public boolean hasRecordsCached() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'recordsCached' field.
      * number of records currently being cached
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder clearRecordsCached() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordsSent' field.
      * number of records sent since application start
      * @return The value.
      */
    public java.lang.Integer getRecordsSent() {
      return recordsSent;
    }

    /**
      * Sets the value of the 'recordsSent' field.
      * number of records sent since application start
      * @param value The value of 'recordsSent'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder setRecordsSent(int value) {
      validate(fields()[3], value);
      this.recordsSent = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'recordsSent' field has been set.
      * number of records sent since application start
      * @return True if the 'recordsSent' field has been set, false otherwise.
      */
    public boolean hasRecordsSent() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'recordsSent' field.
      * number of records sent since application start
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder clearRecordsSent() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'recordsUnsent' field.
      * number of unsent records
      * @return The value.
      */
    public java.lang.Integer getRecordsUnsent() {
      return recordsUnsent;
    }

    /**
      * Sets the value of the 'recordsUnsent' field.
      * number of unsent records
      * @param value The value of 'recordsUnsent'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder setRecordsUnsent(int value) {
      validate(fields()[4], value);
      this.recordsUnsent = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'recordsUnsent' field has been set.
      * number of unsent records
      * @return True if the 'recordsUnsent' field has been set, false otherwise.
      */
    public boolean hasRecordsUnsent() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'recordsUnsent' field.
      * number of unsent records
      * @return This builder.
      */
    public org.radarcns.application.ApplicationRecordCounts.Builder clearRecordsUnsent() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public ApplicationRecordCounts build() {
      try {
        ApplicationRecordCounts record = new ApplicationRecordCounts();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.recordsCached = fieldSetFlags()[2] ? this.recordsCached : (java.lang.Integer) defaultValue(fields()[2]);
        record.recordsSent = fieldSetFlags()[3] ? this.recordsSent : (java.lang.Integer) defaultValue(fields()[3]);
        record.recordsUnsent = fieldSetFlags()[4] ? this.recordsUnsent : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
