/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.application;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Length of application uptime */
@org.apache.avro.specific.AvroGenerated
public class ApplicationUptime extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7204074717091370762L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationUptime\",\"namespace\":\"org.radarcns.application\",\"doc\":\"Length of application uptime\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"uptime\",\"type\":\"double\",\"doc\":\"Time since last app start (s)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** Time since last app start (s) */
  @Deprecated public double uptime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationUptime() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param uptime Time since last app start (s)
   */
  public ApplicationUptime(java.lang.Double time, java.lang.Double timeReceived, java.lang.Double uptime) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.uptime = uptime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return uptime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: uptime = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'uptime' field.
   * @return Time since last app start (s)
   */
  public java.lang.Double getUptime() {
    return uptime;
  }

  /**
   * Sets the value of the 'uptime' field.
   * Time since last app start (s)
   * @param value the value to set.
   */
  public void setUptime(java.lang.Double value) {
    this.uptime = value;
  }

  /**
   * Creates a new ApplicationUptime RecordBuilder.
   * @return A new ApplicationUptime RecordBuilder
   */
  public static org.radarcns.application.ApplicationUptime.Builder newBuilder() {
    return new org.radarcns.application.ApplicationUptime.Builder();
  }

  /**
   * Creates a new ApplicationUptime RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationUptime RecordBuilder
   */
  public static org.radarcns.application.ApplicationUptime.Builder newBuilder(org.radarcns.application.ApplicationUptime.Builder other) {
    return new org.radarcns.application.ApplicationUptime.Builder(other);
  }

  /**
   * Creates a new ApplicationUptime RecordBuilder by copying an existing ApplicationUptime instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationUptime RecordBuilder
   */
  public static org.radarcns.application.ApplicationUptime.Builder newBuilder(org.radarcns.application.ApplicationUptime other) {
    return new org.radarcns.application.ApplicationUptime.Builder(other);
  }

  /**
   * RecordBuilder for ApplicationUptime instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationUptime>
    implements org.apache.avro.data.RecordBuilder<ApplicationUptime> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** Time since last app start (s) */
    private double uptime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.application.ApplicationUptime.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uptime)) {
        this.uptime = data().deepCopy(fields()[2].schema(), other.uptime);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationUptime instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.application.ApplicationUptime other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uptime)) {
        this.uptime = data().deepCopy(fields()[2].schema(), other.uptime);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'uptime' field.
      * Time since last app start (s)
      * @return The value.
      */
    public java.lang.Double getUptime() {
      return uptime;
    }

    /**
      * Sets the value of the 'uptime' field.
      * Time since last app start (s)
      * @param value The value of 'uptime'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder setUptime(double value) {
      validate(fields()[2], value);
      this.uptime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'uptime' field has been set.
      * Time since last app start (s)
      * @return True if the 'uptime' field has been set, false otherwise.
      */
    public boolean hasUptime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'uptime' field.
      * Time since last app start (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationUptime.Builder clearUptime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ApplicationUptime build() {
      try {
        ApplicationUptime record = new ApplicationUptime();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.uptime = fieldSetFlags()[2] ? this.uptime : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
