/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.application;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Server connection status with android client. */
@org.apache.avro.specific.AvroGenerated
public class ApplicationServerStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8512963403158628805L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationServerStatus\",\"namespace\":\"org.radarcns.application\",\"doc\":\"Server connection status with android client.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"serverStatus\",\"type\":{\"type\":\"enum\",\"name\":\"ServerStatus\",\"symbols\":[\"CONNECTED\",\"DISCONNECTED\",\"UNKNOWN\"]},\"doc\":\"server connection status\",\"default\":\"UNKNOWN\"},{\"name\":\"ipAddress\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Hardware identifier of client application\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** server connection status */
  @Deprecated public org.radarcns.application.ServerStatus serverStatus;
  /** Hardware identifier of client application */
  @Deprecated public java.lang.String ipAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationServerStatus() {}

  /**
   * All-args constructor.
   * @param time device timestamp in UTC (s)
   * @param timeReceived device receiver timestamp in UTC (s)
   * @param serverStatus server connection status
   * @param ipAddress Hardware identifier of client application
   */
  public ApplicationServerStatus(java.lang.Double time, java.lang.Double timeReceived, org.radarcns.application.ServerStatus serverStatus, java.lang.String ipAddress) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.serverStatus = serverStatus;
    this.ipAddress = ipAddress;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return serverStatus;
    case 3: return ipAddress;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: serverStatus = (org.radarcns.application.ServerStatus)value$; break;
    case 3: ipAddress = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return device timestamp in UTC (s)
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * @return device receiver timestamp in UTC (s)
   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)
   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'serverStatus' field.
   * @return server connection status
   */
  public org.radarcns.application.ServerStatus getServerStatus() {
    return serverStatus;
  }

  /**
   * Sets the value of the 'serverStatus' field.
   * server connection status
   * @param value the value to set.
   */
  public void setServerStatus(org.radarcns.application.ServerStatus value) {
    this.serverStatus = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return Hardware identifier of client application
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }

  /**
   * Sets the value of the 'ipAddress' field.
   * Hardware identifier of client application
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Creates a new ApplicationServerStatus RecordBuilder.
   * @return A new ApplicationServerStatus RecordBuilder
   */
  public static org.radarcns.application.ApplicationServerStatus.Builder newBuilder() {
    return new org.radarcns.application.ApplicationServerStatus.Builder();
  }

  /**
   * Creates a new ApplicationServerStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationServerStatus RecordBuilder
   */
  public static org.radarcns.application.ApplicationServerStatus.Builder newBuilder(org.radarcns.application.ApplicationServerStatus.Builder other) {
    return new org.radarcns.application.ApplicationServerStatus.Builder(other);
  }

  /**
   * Creates a new ApplicationServerStatus RecordBuilder by copying an existing ApplicationServerStatus instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationServerStatus RecordBuilder
   */
  public static org.radarcns.application.ApplicationServerStatus.Builder newBuilder(org.radarcns.application.ApplicationServerStatus other) {
    return new org.radarcns.application.ApplicationServerStatus.Builder(other);
  }

  /**
   * RecordBuilder for ApplicationServerStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationServerStatus>
    implements org.apache.avro.data.RecordBuilder<ApplicationServerStatus> {

    /** device timestamp in UTC (s) */
    private double time;
    /** device receiver timestamp in UTC (s) */
    private double timeReceived;
    /** server connection status */
    private org.radarcns.application.ServerStatus serverStatus;
    /** Hardware identifier of client application */
    private java.lang.String ipAddress;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.application.ApplicationServerStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serverStatus)) {
        this.serverStatus = data().deepCopy(fields()[2].schema(), other.serverStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[3].schema(), other.ipAddress);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationServerStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.application.ApplicationServerStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serverStatus)) {
        this.serverStatus = data().deepCopy(fields()[2].schema(), other.serverStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[3].schema(), other.ipAddress);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * device timestamp in UTC (s)
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * device timestamp in UTC (s)
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * device timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return The value.
      */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }

    /**
      * Sets the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @param value The value of 'timeReceived'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timeReceived' field has been set.
      * device receiver timestamp in UTC (s)
      * @return True if the 'timeReceived' field has been set, false otherwise.
      */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timeReceived' field.
      * device receiver timestamp in UTC (s)
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'serverStatus' field.
      * server connection status
      * @return The value.
      */
    public org.radarcns.application.ServerStatus getServerStatus() {
      return serverStatus;
    }

    /**
      * Sets the value of the 'serverStatus' field.
      * server connection status
      * @param value The value of 'serverStatus'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder setServerStatus(org.radarcns.application.ServerStatus value) {
      validate(fields()[2], value);
      this.serverStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'serverStatus' field has been set.
      * server connection status
      * @return True if the 'serverStatus' field has been set, false otherwise.
      */
    public boolean hasServerStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'serverStatus' field.
      * server connection status
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder clearServerStatus() {
      serverStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * Hardware identifier of client application
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }

    /**
      * Sets the value of the 'ipAddress' field.
      * Hardware identifier of client application
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder setIpAddress(java.lang.String value) {
      validate(fields()[3], value);
      this.ipAddress = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * Hardware identifier of client application
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * Hardware identifier of client application
      * @return This builder.
      */
    public org.radarcns.application.ApplicationServerStatus.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ApplicationServerStatus build() {
      try {
        ApplicationServerStatus record = new ApplicationServerStatus();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.serverStatus = fieldSetFlags()[2] ? this.serverStatus : (org.radarcns.application.ServerStatus) defaultValue(fields()[2]);
        record.ipAddress = fieldSetFlags()[3] ? this.ipAddress : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
