/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.empatica;  
@SuppressWarnings("all")
/** Data from photoplethysmograph. */
@org.apache.avro.specific.AvroGenerated
public class EmpaticaE4BloodVolumePulse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmpaticaE4BloodVolumePulse\",\"namespace\":\"org.radarcns.empatica\",\"doc\":\"Data from photoplethysmograph.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"bloodVolumePulse\",\"type\":\"float\",\"doc\":\"light absorption (nW)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** light absorption (nW) */
  @Deprecated public float bloodVolumePulse;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EmpaticaE4BloodVolumePulse() {}

  /**
   * All-args constructor.
   */
  public EmpaticaE4BloodVolumePulse(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float bloodVolumePulse) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.bloodVolumePulse = bloodVolumePulse;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return bloodVolumePulse;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: bloodVolumePulse = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'bloodVolumePulse' field.
   * light absorption (nW)   */
  public java.lang.Float getBloodVolumePulse() {
    return bloodVolumePulse;
  }

  /**
   * Sets the value of the 'bloodVolumePulse' field.
   * light absorption (nW)   * @param value the value to set.
   */
  public void setBloodVolumePulse(java.lang.Float value) {
    this.bloodVolumePulse = value;
  }

  /** Creates a new EmpaticaE4BloodVolumePulse RecordBuilder */
  public static org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder newBuilder() {
    return new org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder();
  }
  
  /** Creates a new EmpaticaE4BloodVolumePulse RecordBuilder by copying an existing Builder */
  public static org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder newBuilder(org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder other) {
    return new org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder(other);
  }
  
  /** Creates a new EmpaticaE4BloodVolumePulse RecordBuilder by copying an existing EmpaticaE4BloodVolumePulse instance */
  public static org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder newBuilder(org.radarcns.empatica.EmpaticaE4BloodVolumePulse other) {
    return new org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder(other);
  }
  
  /**
   * RecordBuilder for EmpaticaE4BloodVolumePulse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmpaticaE4BloodVolumePulse>
    implements org.apache.avro.data.RecordBuilder<EmpaticaE4BloodVolumePulse> {

    private double time;
    private double timeReceived;
    private float bloodVolumePulse;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.empatica.EmpaticaE4BloodVolumePulse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bloodVolumePulse)) {
        this.bloodVolumePulse = data().deepCopy(fields()[2].schema(), other.bloodVolumePulse);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EmpaticaE4BloodVolumePulse instance */
    private Builder(org.radarcns.empatica.EmpaticaE4BloodVolumePulse other) {
            super(org.radarcns.empatica.EmpaticaE4BloodVolumePulse.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bloodVolumePulse)) {
        this.bloodVolumePulse = data().deepCopy(fields()[2].schema(), other.bloodVolumePulse);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'bloodVolumePulse' field */
    public java.lang.Float getBloodVolumePulse() {
      return bloodVolumePulse;
    }
    
    /** Sets the value of the 'bloodVolumePulse' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder setBloodVolumePulse(float value) {
      validate(fields()[2], value);
      this.bloodVolumePulse = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'bloodVolumePulse' field has been set */
    public boolean hasBloodVolumePulse() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'bloodVolumePulse' field */
    public org.radarcns.empatica.EmpaticaE4BloodVolumePulse.Builder clearBloodVolumePulse() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public EmpaticaE4BloodVolumePulse build() {
      try {
        EmpaticaE4BloodVolumePulse record = new EmpaticaE4BloodVolumePulse();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.bloodVolumePulse = fieldSetFlags()[2] ? this.bloodVolumePulse : (java.lang.Float) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
