/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.applicationstatus;  
@SuppressWarnings("all")
/** Length of application uptime */
@org.apache.avro.specific.AvroGenerated
public class ApplicationStatusUptime extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationStatusUptime\",\"namespace\":\"org.radarcns.applicationstatus\",\"doc\":\"Length of application uptime\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"applicationUptime\",\"type\":\"float\",\"doc\":\"Time since last app start (s)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** Time since last app start (s) */
  @Deprecated public float applicationUptime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ApplicationStatusUptime() {}

  /**
   * All-args constructor.
   */
  public ApplicationStatusUptime(java.lang.Double time, java.lang.Double timeReceived, java.lang.Float applicationUptime) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.applicationUptime = applicationUptime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return applicationUptime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: applicationUptime = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'applicationUptime' field.
   * Time since last app start (s)   */
  public java.lang.Float getApplicationUptime() {
    return applicationUptime;
  }

  /**
   * Sets the value of the 'applicationUptime' field.
   * Time since last app start (s)   * @param value the value to set.
   */
  public void setApplicationUptime(java.lang.Float value) {
    this.applicationUptime = value;
  }

  /** Creates a new ApplicationStatusUptime RecordBuilder */
  public static org.radarcns.applicationstatus.ApplicationStatusUptime.Builder newBuilder() {
    return new org.radarcns.applicationstatus.ApplicationStatusUptime.Builder();
  }
  
  /** Creates a new ApplicationStatusUptime RecordBuilder by copying an existing Builder */
  public static org.radarcns.applicationstatus.ApplicationStatusUptime.Builder newBuilder(org.radarcns.applicationstatus.ApplicationStatusUptime.Builder other) {
    return new org.radarcns.applicationstatus.ApplicationStatusUptime.Builder(other);
  }
  
  /** Creates a new ApplicationStatusUptime RecordBuilder by copying an existing ApplicationStatusUptime instance */
  public static org.radarcns.applicationstatus.ApplicationStatusUptime.Builder newBuilder(org.radarcns.applicationstatus.ApplicationStatusUptime other) {
    return new org.radarcns.applicationstatus.ApplicationStatusUptime.Builder(other);
  }
  
  /**
   * RecordBuilder for ApplicationStatusUptime instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationStatusUptime>
    implements org.apache.avro.data.RecordBuilder<ApplicationStatusUptime> {

    private double time;
    private double timeReceived;
    private float applicationUptime;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.applicationstatus.ApplicationStatusUptime.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.applicationstatus.ApplicationStatusUptime.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.applicationUptime)) {
        this.applicationUptime = data().deepCopy(fields()[2].schema(), other.applicationUptime);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ApplicationStatusUptime instance */
    private Builder(org.radarcns.applicationstatus.ApplicationStatusUptime other) {
            super(org.radarcns.applicationstatus.ApplicationStatusUptime.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.applicationUptime)) {
        this.applicationUptime = data().deepCopy(fields()[2].schema(), other.applicationUptime);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'applicationUptime' field */
    public java.lang.Float getApplicationUptime() {
      return applicationUptime;
    }
    
    /** Sets the value of the 'applicationUptime' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder setApplicationUptime(float value) {
      validate(fields()[2], value);
      this.applicationUptime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'applicationUptime' field has been set */
    public boolean hasApplicationUptime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'applicationUptime' field */
    public org.radarcns.applicationstatus.ApplicationStatusUptime.Builder clearApplicationUptime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ApplicationStatusUptime build() {
      try {
        ApplicationStatusUptime record = new ApplicationStatusUptime();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.applicationUptime = fieldSetFlags()[2] ? this.applicationUptime : (java.lang.Float) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
