/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.empaticaE4;  
@SuppressWarnings("all")
/** Sensor status according to the device. */
@org.apache.avro.specific.AvroGenerated
public class EmpaticaE4SensorStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmpaticaE4SensorStatus\",\"namespace\":\"org.radarcns.empaticaE4\",\"doc\":\"Sensor status according to the device.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"},{\"name\":\"sensor\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"sensor name; one of BVP, GSR, ACC, TEMP.\"},{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"sensor status; one of NOT_ON_WRIST, ON_WRIST, DEAD.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;
  /** sensor name; one of BVP, GSR, ACC, TEMP. */
  @Deprecated public java.lang.String sensor;
  /** sensor status; one of NOT_ON_WRIST, ON_WRIST, DEAD. */
  @Deprecated public java.lang.String status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EmpaticaE4SensorStatus() {}

  /**
   * All-args constructor.
   */
  public EmpaticaE4SensorStatus(java.lang.Double time, java.lang.Double timeReceived, java.lang.String sensor, java.lang.String status) {
    this.time = time;
    this.timeReceived = timeReceived;
    this.sensor = sensor;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    case 2: return sensor;
    case 3: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    case 2: sensor = (java.lang.String)value$; break;
    case 3: status = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /**
   * Gets the value of the 'sensor' field.
   * sensor name; one of BVP, GSR, ACC, TEMP.   */
  public java.lang.String getSensor() {
    return sensor;
  }

  /**
   * Sets the value of the 'sensor' field.
   * sensor name; one of BVP, GSR, ACC, TEMP.   * @param value the value to set.
   */
  public void setSensor(java.lang.String value) {
    this.sensor = value;
  }

  /**
   * Gets the value of the 'status' field.
   * sensor status; one of NOT_ON_WRIST, ON_WRIST, DEAD.   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * sensor status; one of NOT_ON_WRIST, ON_WRIST, DEAD.   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /** Creates a new EmpaticaE4SensorStatus RecordBuilder */
  public static org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder newBuilder() {
    return new org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder();
  }
  
  /** Creates a new EmpaticaE4SensorStatus RecordBuilder by copying an existing Builder */
  public static org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder newBuilder(org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder other) {
    return new org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder(other);
  }
  
  /** Creates a new EmpaticaE4SensorStatus RecordBuilder by copying an existing EmpaticaE4SensorStatus instance */
  public static org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder newBuilder(org.radarcns.empaticaE4.EmpaticaE4SensorStatus other) {
    return new org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder(other);
  }
  
  /**
   * RecordBuilder for EmpaticaE4SensorStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmpaticaE4SensorStatus>
    implements org.apache.avro.data.RecordBuilder<EmpaticaE4SensorStatus> {

    private double time;
    private double timeReceived;
    private java.lang.String sensor;
    private java.lang.String status;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.empaticaE4.EmpaticaE4SensorStatus.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sensor)) {
        this.sensor = data().deepCopy(fields()[2].schema(), other.sensor);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EmpaticaE4SensorStatus instance */
    private Builder(org.radarcns.empaticaE4.EmpaticaE4SensorStatus other) {
            super(org.radarcns.empaticaE4.EmpaticaE4SensorStatus.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sensor)) {
        this.sensor = data().deepCopy(fields()[2].schema(), other.sensor);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'sensor' field */
    public java.lang.String getSensor() {
      return sensor;
    }
    
    /** Sets the value of the 'sensor' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder setSensor(java.lang.String value) {
      validate(fields()[2], value);
      this.sensor = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'sensor' field has been set */
    public boolean hasSensor() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'sensor' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder clearSensor() {
      sensor = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.String getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder setStatus(java.lang.String value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'status' field */
    public org.radarcns.empaticaE4.EmpaticaE4SensorStatus.Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public EmpaticaE4SensorStatus build() {
      try {
        EmpaticaE4SensorStatus record = new EmpaticaE4SensorStatus();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        record.sensor = fieldSetFlags()[2] ? this.sensor : (java.lang.String) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
