/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.empaticaE4;  
@SuppressWarnings("all")
/** Event mark corresponding to a physical button press on the device; the same time as the status LED is first illuminated. The time is synchronized with initial time of the session indicated in the related data files from the corresponding session. */
@org.apache.avro.specific.AvroGenerated
public class EmpaticaE4Tag extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmpaticaE4Tag\",\"namespace\":\"org.radarcns.empaticaE4\",\"doc\":\"Event mark corresponding to a physical button press on the device; the same time as the status LED is first illuminated. The time is synchronized with initial time of the session indicated in the related data files from the corresponding session.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"device timestamp in UTC (s)\"},{\"name\":\"timeReceived\",\"type\":\"double\",\"doc\":\"device receiver timestamp in UTC (s)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** device timestamp in UTC (s) */
  @Deprecated public double time;
  /** device receiver timestamp in UTC (s) */
  @Deprecated public double timeReceived;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EmpaticaE4Tag() {}

  /**
   * All-args constructor.
   */
  public EmpaticaE4Tag(java.lang.Double time, java.lang.Double timeReceived) {
    this.time = time;
    this.timeReceived = timeReceived;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return timeReceived;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: timeReceived = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * device timestamp in UTC (s)   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * device timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   */
  public java.lang.Double getTimeReceived() {
    return timeReceived;
  }

  /**
   * Sets the value of the 'timeReceived' field.
   * device receiver timestamp in UTC (s)   * @param value the value to set.
   */
  public void setTimeReceived(java.lang.Double value) {
    this.timeReceived = value;
  }

  /** Creates a new EmpaticaE4Tag RecordBuilder */
  public static org.radarcns.empaticaE4.EmpaticaE4Tag.Builder newBuilder() {
    return new org.radarcns.empaticaE4.EmpaticaE4Tag.Builder();
  }
  
  /** Creates a new EmpaticaE4Tag RecordBuilder by copying an existing Builder */
  public static org.radarcns.empaticaE4.EmpaticaE4Tag.Builder newBuilder(org.radarcns.empaticaE4.EmpaticaE4Tag.Builder other) {
    return new org.radarcns.empaticaE4.EmpaticaE4Tag.Builder(other);
  }
  
  /** Creates a new EmpaticaE4Tag RecordBuilder by copying an existing EmpaticaE4Tag instance */
  public static org.radarcns.empaticaE4.EmpaticaE4Tag.Builder newBuilder(org.radarcns.empaticaE4.EmpaticaE4Tag other) {
    return new org.radarcns.empaticaE4.EmpaticaE4Tag.Builder(other);
  }
  
  /**
   * RecordBuilder for EmpaticaE4Tag instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmpaticaE4Tag>
    implements org.apache.avro.data.RecordBuilder<EmpaticaE4Tag> {

    private double time;
    private double timeReceived;

    /** Creates a new Builder */
    private Builder() {
      super(org.radarcns.empaticaE4.EmpaticaE4Tag.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.radarcns.empaticaE4.EmpaticaE4Tag.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EmpaticaE4Tag instance */
    private Builder(org.radarcns.empaticaE4.EmpaticaE4Tag other) {
            super(org.radarcns.empaticaE4.EmpaticaE4Tag.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timeReceived)) {
        this.timeReceived = data().deepCopy(fields()[1].schema(), other.timeReceived);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Double getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public org.radarcns.empaticaE4.EmpaticaE4Tag.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public org.radarcns.empaticaE4.EmpaticaE4Tag.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timeReceived' field */
    public java.lang.Double getTimeReceived() {
      return timeReceived;
    }
    
    /** Sets the value of the 'timeReceived' field */
    public org.radarcns.empaticaE4.EmpaticaE4Tag.Builder setTimeReceived(double value) {
      validate(fields()[1], value);
      this.timeReceived = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timeReceived' field has been set */
    public boolean hasTimeReceived() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timeReceived' field */
    public org.radarcns.empaticaE4.EmpaticaE4Tag.Builder clearTimeReceived() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public EmpaticaE4Tag build() {
      try {
        EmpaticaE4Tag record = new EmpaticaE4Tag();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.timeReceived = fieldSetFlags()[1] ? this.timeReceived : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
